package com.ybwh.dsl.jdbc.core.statement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Objects;

import com.ybwh.dsl.api.interceptor.StatementInterceptor;
import com.ybwh.dsl.jdbc.adapter.AbstractDelegatingConnectionAdapter;
import com.ybwh.dsl.jdbc.adapter.AbstractDelegatingStatementAdapter;

public class DefaultDelegatingStatement extends AbstractDelegatingStatementAdapter {
	private List<StatementInterceptor> statementInterceptors;

	public DefaultDelegatingStatement(Statement stmt, AbstractDelegatingConnectionAdapter conn,
			List<StatementInterceptor> statementInterceptors) {
		super(stmt, conn);
		Objects.requireNonNull(statementInterceptors);
		this.statementInterceptors = statementInterceptors;
		
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

}
